### ISSUE TITLE
issue with postgres

### ISSUE THREAD

**Issue by sjooker** [tomatophp/filament-notes#1]
SQLSTATE[42883]: Undefined function: 7 ERREUR: l'opérateur n'existe pas : json = unknown LINE 1: ...d" = "note_metas"."note_id" and "key" = $4 and "value" = $5) ^ HINT: Aucun opérateur ne correspond au nom donné et aux types d'arguments. Vous devez ajouter des conversions explicites de type. (Connection: pgsql, SQL: select count(*) as aggregate from "notes" where "is_public" = 1 or "user_id" = 1 or "is_public" = 0 and exists (select * from "note_metas" where "notes"."id" = "note_metas"."note_id" and "key" = App\Models\User and "value" = 1))

**Comment by 3x1io** [comment]
hi @sjooker thanks for your report, do you have a full tracing for this error? and can it be in English, please?

**Comment by sjooker** [comment]
Application
Routing

controller

TomatoPHP\FilamentNotes\Filament\Resources\NoteResource\Pages\ManageNotes@__invoke

route name

filament.admin.resources.notes.index

middleware

panel:admin, Illuminate\Cookie\Middleware\EncryptCookies, Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse, Illuminate\Session\Middleware\StartSession, Illuminate\Session\Middleware\AuthenticateSession, Illuminate\View\Middleware\ShareErrorsFromSession, Illuminate\Foundation\Http\Middleware\VerifyCsrfToken, Illuminate\Routing\Middleware\SubstituteBindings, Filament\Http\Middleware\DisableBladeIconComponents, Filament\Http\Middleware\DispatchServingFilamentEvent, Filament\Http\Middleware\Authenticate

Database Queries

pgsql (36.11 ms)

select * from "sessions" where "id" = 'ijvVQjtUFCa7uaBhy7OV3nvqJ2HZcUJqHCqDnWP4' limit 1

pgsql (1.37 ms)

select * from "roles" where ("name" = 'panel_user') limit 1

pgsql (0.97 ms)

select * from "users" where "id" = 1 limit 1

pgsql (1.12 ms)

select "roles".*, "model_has_roles"."model_id" as "pivot_model_id", "model_has_roles"."role_id" as "pivot_role_id", "model_has_roles"."model_type" as "pivot_model_type" from "roles" inner join "model_has_roles" on "roles"."id" = "model_has_roles"."role_id" where "model_has_roles"."model_id" in (1) and "model_has_roles"."model_type" = 'App\Models\User'

pgsql (1.07 ms)

select * from "cache" where "key" = 'spatie.permission.cache' limit 1

pgsql (0.4 ms)

select * from "cache" where "key" = '5ebec309c160489a120f3ce4149da939df30eadb' limit 1

pgsql (0.2 ms)

select * from "cache" where "key" = 'f04f95835b37fe53d95e2492acef9eeeef9e018c' limit 1

**Comment by 3x1io** [comment]
and the main error is? in English

**Comment by 3x1io** [comment]
okay i think the problem was just migrations file and you try it now and let me know?
