### ISSUE TITLE
could not find driver error

### ISSUE THREAD

**Issue by erdalqc** [tomatophp/filament-notes#13]
I get this error after installing 

"could not find driver"

**Comment by 3x1io** [comment]
please allow SQLite3 ex or PHP

**Comment by erdalqc** [comment]
> please allow SQLite3 ex or PHP
I'm sorry, I used mysql in my project, how can I do what you said?

**Comment by 3x1io** [comment]
it's ok just allow the ex it's for caching.

**Comment by 3x1io** [comment]
that's mean you need SQLite3 Ex that's it, the driver try to fund icons table on my the driver and it's not exists!

**Comment by rsahrudin-sif** [comment]
> now i have receiving an error like below [SQLSTATE[HY000]: General error: 1 no such table: icons (Connection: , SQL: select "label", "name" from "icons" limit 10)](https://172.16.0.4/admin/notes#top)

I also experienced the same thing, how do I fix it?

**Comment by 3x1io** [comment]
with the same way make sure that you have `SQLite3` Ex for PHP on your ini

**Comment by erdalqc** [comment]
> with the same way make sure that you have `SQLite3` Ex for PHP on your ini
![error](https://github.com/user-attachments/assets/a314e051-62a4-4e20-b96d-8e0adc9c8355)

I still get the same error even though I did it a long time ago.

**Comment by 3x1io** [comment]
it's okay now try to clear you cache

```bash
php artisan filament:optimize-clear
php artisan filament-icons:cache
```

**Comment by erdalqc** [comment]
> ```shell
> php artisan filament-icons:cache
> ```
finally it worked thank you great person

**Comment by erdalqc** [comment]
There was a problem. When I used it as a widget, the page structure was broken as attached file
![page](https://github.com/user-attachments/assets/0c54d02e-b1f8-44fd-88b9-d9c64118b7b8)
