### ISSUE TITLE
Error Click New Note

### ISSUE THREAD

**Issue by rsahrudin-sif** [tomatophp/filament-notes#14]
When I click on new note, the following error notification appears. I have followed the guide in the sticky notes plugin installation documentation.

![image](https://github.com/user-attachments/assets/a44a2d1f-2451-4b0c-832c-97610a123a22)

**Comment by 3x1io** [comment]
just allow SQLite3 ex on your PHP .ini file

**Comment by rsahrudin-sif** [comment]
ok works.. thanks

**Comment by rsahrudin-sif** [comment]
![image](https://github.com/user-attachments/assets/c04a8913-3dbb-4c2d-9443-c511155c1937)

Why is it that when I click on new note, the note form modal doesn't appear, even though previously it was normal without any problems?

**Comment by rsahrudin-sif** [comment]
![image](https://github.com/user-attachments/assets/fa63d514-ae98-49c0-bc8c-fd2d7c3eba01)

when I click on new note
