### ISSUE TITLE
Icon Issue

### ISSUE THREAD

**Issue by AhmedNabil1992** [tomatophp/filament-notes#2]
i face issue after i create note 
svg(): Argument #1 ($name) must be of type string, null given,
\resources\views\vendor\filament\components\icon.blade.php :24

Widget list and also note list , i try to create note with and without icon and same error

**Comment by 3x1io** [comment]
okay, it was an update on filament-icons, filament-type and now it's fine just use composer update. and let me know if it's still exists.

**Comment by AhmedNabil1992** [comment]
thanks for respond ,
i try composer update and issue still exist ,

![image](https://github.com/user-attachments/assets/691f6464-0d61-435a-9922-27630e3f358b)

**Comment by 3x1io** [comment]
fixed in v1.0.7

**Comment by paulmercs** [comment]
why i have this error?
SQLSTATE[HY000]: General error: 1 no such table: icons 

when i am going to create new note?
![Screenshot 2024-07-24 202424](https://github.com/user-attachments/assets/6618f356-b6f8-4ccf-b277-c477436b48eb)

**Comment by 3x1io** [comment]
you need sqlite3 ext on your php

**Comment by 3x1io** [comment]
can you try 

```php
php artisan filament-icons:install
```

**Comment by AhmedNabil1992** [comment]
i make update , and try this php artisan filament-icons:install 
also same issue

**Comment by 3x1io** [comment]
@AhmedNabil1992 @paulmercs what is your database driver?

**Comment by paulmercs** [comment]
![image](https://github.com/user-attachments/assets/ae2ac2c4-9a92-471b-a93a-5097dc31c0f4)

i am using mysql

**Comment by AhmedNabil1992** [comment]
sql server

**Comment by 3x1io** [comment]
please provide the FilamentPHP version and PHP version because I tried it and I don't get the same error!

**Comment by paulmercs** [comment]
> please provide the FilamentPHP version and PHP version because I tried it and I don't get the same error!

FilamentPHP v3.2.95
PHP v8.3.8

**Comment by 3x1io** [comment]
@AhmedNabil1992 It's okay because it's just a SQLite caching file so you don't get any tables on your database.

**Comment by AhmedNabil1992** [comment]
php -v
PHP 8.2.20
Filament v 3.2.96

**Comment by 3x1io** [comment]
@AhmedNabil1992 @paulmercs do you try composer update?

**Comment by AhmedNabil1992** [comment]
yes

**Comment by paulmercs** [comment]
> @AhmedNabil1992 @paulmercs do you try composer update?

done that already.

**Comment by 3x1io** [comment]
okay i will check it again on a fresh install

**Comment by 3x1io** [comment]
![Screenshot 2024-07-24 at 3 54 50 PM](https://github.com/user-attachments/assets/99fd66b8-a5cc-4774-bc4a-866f91dae080)

@AhmedNabil1992 @paulmercs you get this problem when create a new note with icon?

**Comment by AhmedNabil1992** [comment]
i try now fresh install , but there is error 
![image](https://github.com/user-attachments/assets/e0a0b855-2368-4f95-a0e6-c04ce43c19a7)

**Comment by 3x1io** [comment]
@AhmedNabil1992 do you have the same?

**Comment by 3x1io** [comment]
@paulmercs i think your problem still with SQLite3 so if you can try to use SQLite3 as a database and check it works or not.

**Comment by paulmercs** [comment]
> @paulmercs i think your problem still with SQLite3 so if you can try to use SQLite3 as a database and check it works or not.

will try it fresh install

**Comment by AhmedNabil1992** [comment]
when i change database connection on fresh install to sql server it`s worked , but on another project same error , 
try remove and install again ?

**Comment by paulmercs** [comment]
same as mine

**Comment by 3x1io** [comment]
I think it's maybe a version problem, but for now, @AhmedNabil1992 @paulmercs it's working on a freshly installed project?

**Comment by AhmedNabil1992** [comment]
> I think it's maybe a version problem, but for now, @AhmedNabil1992 @paulmercs it's working on a freshly installed project?

Yes , on both db connection

**Comment by OccTherapist** [comment]
> ![image](https://private-user-images.githubusercontent.com/136664232/351723825-233da8b1-a249-4000-9819-4a5ea34c9604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMjA2OTQsIm5iZiI6MTcyMjEyMDM5NCwicGF0aCI6Ii8xMzY2NjQyMzIvMzUxNzIzODI1LTIzM2RhOGIxLWEyNDktNDAwMC05ODE5LTRhNWVhMzRjOTYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QyMjQ2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWJmZGYyYmU4ZDUyZDJkOGE1MDg1MjA1MGQyYWUzOGI0OTMzYzk2YjgyYmJhMDkwYzlkYTVlYjRkZGM4YWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T-xDtykkBPW9POoH-oILpCuWbDfubrweNpyIRrefP2g)
> 
> i cannot create a note because of this error. i installed the plugin in my existing project.
> 
> also i update the plugin to 1.0.9 same issue

I have the same issue on the production environment. On local it works fine. sqlite3 extension is installed on both systems, also tested with php 8.2 and 8.3

**Comment by OccTherapist** [comment]
I managed to make it work.

I run following commands:

`php artisan filament-icons:clear`

and then

`php artisan filament-icons:install`

**Comment by 3x1io** [comment]
@OccTherapist thanks for your help and support I think that's it, a cache of filament-icons I will run this commands on an install command for Filament Notes to make sure that the icons is working fine
