### ISSUE TITLE
Livewire component

### ISSUE THREAD

**Issue by willcastillo** [tomatophp/filament-notes#5]
Hello,

The documentation says that I need to add this to the blade file:
`<livewire:note-action :note="$note" />`
... but I don't know what to send back as `$note`.

Similarly, the documentation says that I can use it as a widget by registering it in the panel... but that doesn't seem to be enough.

Do you have/can provide a simple demo project please? This looks like a nice plugin to use but I don't think to follow the docs correcly.

Thanks,

**Comment by 3x1io** [comment]
$note is the object of the Note Model, I will add this to docs and we have a demo.

https://filament-notes.tomatophp.com

you can try it

**Comment by 3x1io** [comment]
it exists as an open source.

https://github.com/tomatophp/filament-notes-demo
