### ISSUE TITLE
Bug Report: Tooltip Stuck When Opening Message

### ISSUE THREAD

**Issue by edeoliv** [tomatophp/filament-notes#8]
When opening a message, the tooltip for the `Edit` button remains visible and `sticks` to the screen, even after the message is opened. This creates a visual distraction and impacts the user experience.

![imagen](https://github.com/user-attachments/assets/8cbc4ba7-b153-4a0e-9eeb-34990d45cac1)

**Comment by 3x1io** [comment]
i think the problem is from Filament Panel itself because this happen after the last update of filament

**Comment by 3x1io** [comment]
we just fix it by hide the tooltip for now till get fix from Filament
